name: Swagger Deploy

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        name: Deploy Swagger File
        steps:
          - name: Checkout    
            uses: actions/checkout@v3 

          - name: Sync Files
            uses: burnett01/rsync-deployments@5.2.1
            with:
                path: ./
                switches: -avzr --delete --exclude=".git*" --exclude="*.md"
                remote_host: ${{ secrets.DOCS_HOST }}
                remote_user: ${{ secrets.DOCS_USER }}
                remote_key: ${{ secrets.DOCS_SSH_KEY }}
                remote_key_pass: ${{ secrets.DOCS_SSH_KEY_PASS }}
                remote_path: ~/docs/
